### PR TITLE
Added Initial Website

### PR DESCRIPTION
**Pull request by KrishSavani**
Done:

- [x] Add a landing page
- [x] Add information about the club and its perspective
- [x] Updates from the club
- [x] Socials etc

Remaining:

- [ ] Updating Updates Section
- [ ] Responsiveness
- [ ] Dark Mode

### CODE REVIEW

**Review by nimit2801 — COMMENTED** [review]
Hey, can you add the screenshot of the output attaching with this PR?

**Comment by KrishSavani** [comment]
Sure, Here is just the landing page.
output

**Comment by nimit2801** [comment]
> 
> 
> Sure, Here is just the landing page.
> output

Hey, this looks amazing! I;ll review the files add merge the PR

**Review by nimit2801 — APPROVED** [review]
LGTM! 👍 
Thanks for the contribution ✅

**Comment by KrishSavani** [comment]
Looking forward to contribute more!
Can u please make two issues as:

1. Make Responsive
2. Dark Mode

**Comment by nimit2801** [comment]
Can you add all the files from `DSCNUV_Website` to the `root folder`

**Pull request merged**
